# Generated by Django 4.0.5 on 2022-07-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_n', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_1', models.PositiveBigIntegerField()),
                ('mobile_2', models.PositiveBigIntegerField(null=True)),
                ('zip_code', models.SmallIntegerField()),
                ('address_street', models.CharField(max_length=200)),
                ('address_num', models.IntegerField()),
                ('address_floor', models.CharField(max_length=10, null=True)),
                ('address_ap', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_details', to='therapists.therapists')),
            ],
        ),
    ]
