# Generated by Django 4.0.5 on 2022-07-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_1', models.PositiveBigIntegerField()),
                ('mobile_2', models.PositiveBigIntegerField(null=True)),
                ('zip_code', models.SmallIntegerField()),
                ('address_street', models.CharField(max_length=200)),
                ('address_num', models.IntegerField()),
                ('address_floor', models.CharField(max_length=10, null=True)),
                ('address_ap', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_n', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recurrent', models.BooleanField(default=False)),
                ('day_start', models.DateField()),
                ('day_end', models.DateField(null=True)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_shift', to='patients.rooms')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_shift', to='therapists.therapists')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guardian', models.IntegerField(choices=[(1, 'No'), (2, 'Yes')])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sessions', to='patients.patients')),
                ('therapist', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='therapist_session', to='therapists.therapists')),
            ],
        ),
    ]
