# Generated by Django 4.0.5 on 2022-07-04 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='created_by_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patients',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('DELETED'), related_name='updated_by_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_details', to='patients.patients'),
        ),
        migrations.AlterUniqueTogether(
            name='shifts',
            unique_together={('room', 'day_start', 'time_start')},
        ),
    ]
