# Generated by Django 4.0.5 on 2022-07-11 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patients_id_document_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
