# Generated by Django 4.0.5 on 2022-07-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patients_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
