# Generated by Django 4.0.5 on 2022-07-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patients_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='id_document_n',
            field=models.IntegerField(unique=True),
        ),
    ]
